---
# file: deploy.yml

- name: Deploy fronend server
  hosts: front

  tasks:
  - name: Ensure nginx is at the latest version
    ansible.builtin.apt:
      update_cache: yes
      name: nginx
      state: latest
  - name: Write the nginx config file
    ansible.builtin.copy:
      src: ./front/nginx_conf/site.conf
      dest: /etc/nginx/sites-enabled/
  - name: Remove nginx default virtualhost
    ansible.builtin.file:
      path: /etc/nginx/sites-enabled/default
      state: absent
  - name: Add site files
    ansible.builtin.copy:
      src: ./front/site_static/
      dest: /var/www/html/site/
      owner: root
      group: www-data
      mode: 0644
  - name: Start nginx
    ansible.builtin.command:
      argv:
        - nginx


- name: Deploy backend server
  hosts: back

  tasks:
  - name: Ensure php-fpm is at the latest version
    ansible.builtin.apt:
      update_cache: yes
      name: php-fpm
      state: latest
  - name: Remove fpm www pool
    ansible.builtin.file:
      path: /etc/php/7.4/fpm/pool.d/www.conf
      state: absent
  - name: Write the php-fpm pool template
    ansible.builtin.template:
      src: ./back/site.j2
      dest: /etc/php/7.4/fpm/pool.d/site.conf
  - name: Start php-fpm
    ansible.builtin.command:
      argv:
        - php-fpm7.4
        - -F
