version: "3.9"

services:
  front1:
    container_name: "front1.${BUILD_NUMBER}"
    privileged: true
    build:
      context: .
    ports:
      - "22001:22"
      - "9280:80"
    command: /usr/sbin/sshd -D -f /etc/ssh/sshd_config
    volumes:
      - type: volume
        source: front1www5
        target: /var/www/html/site
  back1:
    container_name: "back1.${BUILD_NUMBER}"
    hostname: back1-add
    privileged: true
    build:
      context: .
    ports:
      - "22002:22"
      - "9000"
    volumes:
      - front1www5:/var/www/html/site
    command: /usr/sbin/sshd -D -f /etc/ssh/sshd_config
  back2:
    container_name: "back2.${BUILD_NUMBER}"
    hostname: back2-multiply
    privileged: true
    build:
      context: .
    ports:
      - "22003:22"
      - "9001"
    volumes:
      - front1www5:/var/www/html/site
    command: /usr/sbin/sshd -D -f /etc/ssh/sshd_config

volumes:
  front1www5:
